#!/usr/bin/env python3
"""
audit-blocks.py — .deco block auditor for deco.cx projects

Usage: python3 scripts/audit-blocks.py [project_root]
       project_root defaults to the current directory

Output: text report with removal candidates in 4 categories.
"""

import os
import sys
import json
import urllib.parse
from collections import defaultdict

LEGACY_PATTERNS = [
    'teste', 'test ', 'teste a/b', 'teste ab', 'testab',
    'legacy', 'legado', 'backup', 'bkp',
    'exemplo', 'example',
    ' old', '-old', '_old',
    'antigo',
]

PAGE_TYPE = 'website/pages/Page.tsx'
AB_MATCHER_TYPE = 'website/matchers/random.ts'
REDIRECT_TYPE = 'website/loaders/redirect.ts'

# Block types that are referenced through global config, not page sections.
# These will show as "orphan" in section checks but are NOT truly unused.
GLOBAL_BLOCK_TYPES = {
    'website/loaders/secret.ts',       # API keys / secrets
    'website/loaders/fonts/googleFonts.ts',
    'site/apps/site.ts',
    'site/apps/algolia-raiz.ts',
    'site/apps/workflow-raiz.ts',
    'site/apps/deco/algolia.ts',
    'site/apps/deco/analytics.ts',
    'site/apps/deco/sourei.ts',
    'site/apps/deco/vtex.ts',
    'site/apps/deco/workflows.ts',
    'decohub/apps/commerce.ts',
    'sourei/sections/Analytics/Sourei.tsx',
    'deco-sites/std/sections/Analytics.tsx',
    'deco-sites/std/sections/SEO.tsx',
    'website/sections/Analytics/Analytics.tsx',
    'analytics/loaders/DecoAnalyticsScript.ts',
    'vtex/workflows/events.ts',
    # Redirect loaders are referenced by routes, not sections
    'site/loaders/redirectsFromCsv.ts',
    'deco-sites/std/loaders/x/redirects.ts',
}

# Blocks whose name starts with "Preview " are auto-generated by deco admin.
def is_preview_block(name: str) -> bool:
    return name.startswith('Preview ')


def load_blocks(blocks_dir: str) -> list[dict]:
    blocks = []
    for fname in sorted(os.listdir(blocks_dir)):
        path = os.path.join(blocks_dir, fname)
        if not fname.endswith('.json'):
            continue
        try:
            with open(path, encoding='utf-8') as f:
                data = json.load(f)
        except Exception as e:
            print(f"  [WARN] Could not parse {fname}: {e}", file=sys.stderr)
            continue
        blocks.append({
            'file': fname,
            'decoded': urllib.parse.unquote(fname.replace('.json', '')),
            'path': path,
            'data': data,
            'resolve_type': data.get('__resolveType', ''),
        })
    return blocks


def collect_referenced_block_names(blocks: list[dict]) -> set[str]:
    """Collect all block names referenced in page sections."""
    referenced = set()
    for b in blocks:
        if b['resolve_type'] == PAGE_TYPE:
            for section in b['data'].get('sections', []):
                if not isinstance(section, dict):
                    continue
                rt = section.get('__resolveType', '')
                if rt:
                    referenced.add(rt)
    return referenced


def is_legacy(name: str) -> bool:
    lower = name.lower()
    return any(p in lower for p in LEGACY_PATTERNS)


def audit(project_root: str) -> None:
    blocks_dir = os.path.join(project_root, '.deco', 'blocks')
    if not os.path.isdir(blocks_dir):
        print(f"ERROR: .deco/blocks not found in {project_root}")
        sys.exit(1)

    blocks = load_blocks(blocks_dir)
    referenced_names = collect_referenced_block_names(blocks)

    pages = [b for b in blocks if b['resolve_type'] == PAGE_TYPE]
    ab_matchers = [b for b in blocks if b['resolve_type'] == AB_MATCHER_TYPE]
    redirects = [b for b in blocks if b['resolve_type'] == REDIRECT_TYPE]
    sections = [b for b in blocks if b['resolve_type'] not in (PAGE_TYPE, AB_MATCHER_TYPE, REDIRECT_TYPE, '')]

    # — Orphans ——————————————————————————————————————————————————————————————
    orphan_sections = [
        b for b in sections
        if b['decoded'] not in referenced_names
        and b['resolve_type'] not in referenced_names
        and b['resolve_type'] not in GLOBAL_BLOCK_TYPES
        and not is_preview_block(b['decoded'])
    ]

    # — Legacy/Test ————————————————————————————————————————————————————————
    legacy_blocks = [b for b in blocks if is_legacy(b['decoded'])]

    # — Inactive A/B ————————————————————————————————————————————————————————
    inactive_ab = []
    for b in ab_matchers:
        traffic = b['data'].get('traffic')
        if traffic is not None and (traffic == 0 or traffic == 1 or traffic == 100):
            inactive_ab.append(b)

    # — Duplicate redirects ————————————————————————————————————————————————
    redirect_by_dest: dict[str, list[dict]] = defaultdict(list)
    for b in redirects:
        for rule in b['data'].get('redirects', []) if isinstance(b['data'].get('redirects'), list) else []:
            to = rule.get('to', '')
            if to:
                redirect_by_dest[to].append(b)
    duplicate_redirects = {
        dest: blocks_list
        for dest, blocks_list in redirect_by_dest.items()
        if len(blocks_list) > 1
    }

    # — Report ——————————————————————————————————————————————————————————
    print("=" * 70)
    print("  DECO BLOCK AUDIT")
    print(f"  Project: {project_root}")
    print("=" * 70)
    print(f"\nTotal blocks  : {len(blocks)}")
    print(f"Pages         : {len(pages)}")
    print(f"Sections      : {len(sections)}")
    print(f"A/B Matchers  : {len(ab_matchers)}")
    print(f"Redirects     : {len(redirects)}")

    # Orphans
    print(f"\n{'─'*70}")
    print(f"  ORPHAN SECTIONS ({len(orphan_sections)}) — not referenced by any page")
    print(f"{'─'*70}")
    if orphan_sections:
        for b in orphan_sections:
            print(f"  • {b['decoded']}")
            print(f"    type: {b['resolve_type']}")
    else:
        print("  No orphan sections found.")

    # Legacy
    print(f"\n{'─'*70}")
    print(f"  LEGACY/TEST BLOCKS ({len(legacy_blocks)}) — suspicious names")
    print(f"{'─'*70}")
    if legacy_blocks:
        for b in legacy_blocks:
            is_page = b['resolve_type'] == PAGE_TYPE
            tag = '[PAGE]' if is_page else '[SECTION]' if b['resolve_type'] else '[OTHER]'
            print(f"  • {b['decoded']}  {tag}")
    else:
        print("  No blocks with suspicious names found.")

    # Inactive A/B
    print(f"\n{'─'*70}")
    print(f"  INACTIVE A/B MATCHERS ({len(inactive_ab)}) — traffic=0 or 1/100%")
    print(f"{'─'*70}")
    if inactive_ab:
        for b in inactive_ab:
            traffic = b['data'].get('traffic')
            print(f"  • {b['decoded']}  (traffic={traffic})")
    else:
        print("  No inactive A/B matchers found.")

    # Duplicate redirects
    print(f"\n{'─'*70}")
    print(f"  DUPLICATE REDIRECTS ({len(duplicate_redirects)} destinations)")
    print(f"{'─'*70}")
    if duplicate_redirects:
        for dest, blist in duplicate_redirects.items():
            print(f"  destination: {dest}")
            for b in blist:
                print(f"    • {b['decoded']}")
    else:
        print("  No duplicate redirects found.")

    # Summary
    total_candidates = len(orphan_sections) + len(legacy_blocks) + len(inactive_ab)
    print(f"\n{'='*70}")
    print(f"  TOTAL REMOVAL CANDIDATES: {total_candidates}")
    print(f"  (review manually before deleting)")
    print(f"{'='*70}\n")


if __name__ == '__main__':
    root = sys.argv[1] if len(sys.argv) > 1 else '.'
    audit(root)
